// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Ares.CodeGeneration
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class CheckTransactionByCustomerIdReturnModel
    {
        public System.Int32 TransactionID { get; set; }
        public System.Int32 EmployeeID { get; set; }
        public System.Int32 CustomerID { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public System.Decimal TotalAmount { get; set; }
        public System.Decimal DiscountAmount { get; set; }
        public System.Int32? OrderID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ChangedDate { get; set; }
    }

}
// </auto-generated>
