// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Ares.CodeGeneration
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class GetCustomerReturnModel
    {
        public System.String CustomerName { get; set; }
        public System.Int32 CustomerID { get; set; }
        public System.Int32? TransCount { get; set; }
        public System.Int32? RateLevel { get; set; }
        public System.Int32 DiscountRating { get; set; }
        public System.String Address { get; set; }
    }

}
// </auto-generated>
