// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Ares.CodeGeneration
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class SettlementForCustomerReturnModel
    {
        [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
        public class ResultSetModel1
        {
            public System.Int32? TransYear { get; set; }
            public System.Int32? TransMonth { get; set; }
            public System.Decimal? TotalPay { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel1> ResultSet1;

        [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
        public class ResultSetModel2
        {
            public System.Int32? CustomerID { get; set; }
            public System.String CustomerName { get; set; }
            public System.Decimal? DiscountAmount { get; set; }
            public System.Int32? TransCount { get; set; }
            public System.Decimal? TotalAmount { get; set; }
            public System.Decimal? NeedPay { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel2> ResultSet2;

    }

}
// </auto-generated>
