// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Ares.CodeGeneration
{

    // script_deployments
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class sys_ScriptDeployment
    {
        public System.Guid DeploymentId { get; set; } // deployment_id
        public System.Guid CoordinatorId { get; set; } // coordinator_id
        public string DeploymentName { get; set; } // deployment_name (length: 128)
        public System.DateTimeOffset DeploymentSubmitted { get; set; } // deployment_submitted
        public System.DateTimeOffset? DeploymentStart { get; set; } // deployment_start
        public System.DateTimeOffset? DeploymentEnd { get; set; } // deployment_end
        public string Status { get; set; } // status (length: 128)
        public string ResultsTable { get; set; } // results_table (length: 261)
        public string RetryPolicy { get; set; } // retry_policy (length: 128)
        public string Script { get; set; } // script
        public string Messages { get; set; } // messages
    }

}
// </auto-generated>
