// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Ares.CodeGeneration
{

    // script_deployment_status
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class sys_ScriptDeploymentStatus
    {
        public System.Guid DeploymentId { get; set; } // deployment_id
        public System.Guid? WorkerId { get; set; } // worker_id
        public string LogicalServer { get; set; } // logical_server (length: 128)
        public string DatabaseName { get; set; } // database_name (length: 128)
        public System.DateTimeOffset? DeploymentStart { get; set; } // deployment_start
        public System.DateTimeOffset? DeploymentEnd { get; set; } // deployment_end
        public string Status { get; set; } // status (length: 128)
        public short NumRetries { get; set; } // num_retries
        public string Messages { get; set; } // messages
    }

}
// </auto-generated>
