// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Ares.CodeGeneration
{

    // script_deployments
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class sys_ScriptDeploymentMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<sys_ScriptDeployment>
    {
        public sys_ScriptDeploymentMapping()
            : this("sys")
        {
        }

        public sys_ScriptDeploymentMapping(string schema)
        {
            ToTable("script_deployments", schema);
            HasKey(x => new { x.DeploymentId, x.CoordinatorId, x.DeploymentName, x.DeploymentSubmitted, x.Status, x.RetryPolicy, x.Script });

            Property(x => x.DeploymentId).HasColumnName(@"deployment_id").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.CoordinatorId).HasColumnName(@"coordinator_id").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.DeploymentName).HasColumnName(@"deployment_name").IsRequired().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.DeploymentSubmitted).HasColumnName(@"deployment_submitted").IsRequired().HasColumnType("datetimeoffset");
            Property(x => x.DeploymentStart).HasColumnName(@"deployment_start").IsOptional().HasColumnType("datetimeoffset");
            Property(x => x.DeploymentEnd).HasColumnName(@"deployment_end").IsOptional().HasColumnType("datetimeoffset");
            Property(x => x.Status).HasColumnName(@"status").IsRequired().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.ResultsTable).HasColumnName(@"results_table").IsOptional().HasColumnType("nvarchar").HasMaxLength(261);
            Property(x => x.RetryPolicy).HasColumnName(@"retry_policy").IsRequired().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.Script).HasColumnName(@"script").IsRequired().HasColumnType("nvarchar(max)");
            Property(x => x.Messages).HasColumnName(@"messages").IsOptional().HasColumnType("nvarchar(max)");
        }
    }

}
// </auto-generated>
