// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Ares.CodeGeneration
{

    // script_deployment_status
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class sys_ScriptDeploymentStatusMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<sys_ScriptDeploymentStatus>
    {
        public sys_ScriptDeploymentStatusMapping()
            : this("sys")
        {
        }

        public sys_ScriptDeploymentStatusMapping(string schema)
        {
            ToTable("script_deployment_status", schema);
            HasKey(x => new { x.DeploymentId, x.LogicalServer, x.DatabaseName, x.Status, x.NumRetries });

            Property(x => x.DeploymentId).HasColumnName(@"deployment_id").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.WorkerId).HasColumnName(@"worker_id").IsOptional().HasColumnType("uniqueidentifier");
            Property(x => x.LogicalServer).HasColumnName(@"logical_server").IsRequired().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.DatabaseName).HasColumnName(@"database_name").IsRequired().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.DeploymentStart).HasColumnName(@"deployment_start").IsOptional().HasColumnType("datetimeoffset");
            Property(x => x.DeploymentEnd).HasColumnName(@"deployment_end").IsOptional().HasColumnType("datetimeoffset");
            Property(x => x.Status).HasColumnName(@"status").IsRequired().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.NumRetries).HasColumnName(@"num_retries").IsRequired().HasColumnType("smallint");
            Property(x => x.Messages).HasColumnName(@"messages").IsOptional().HasColumnType("nvarchar(max)");
        }
    }

}
// </auto-generated>
