// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Ares.CodeGeneration
{

    // TransInfoDetail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class TransInfoDetail
    {
        public int TransactionId { get; set; } // TransactionID
        public int EmployeeId { get; set; } // EmployeeID
        public int CustomerId { get; set; } // CustomerID
        public System.DateTime TransactionDateTime { get; set; } // TransactionDateTime
        public decimal TotalAmount { get; set; } // TotalAmount
        public decimal DiscountAmount { get; set; } // DiscountAmount
        public int? OrderId { get; set; } // OrderID
        public bool IsSuccessful { get; set; } // IsSuccessful
        public string EmployeeName { get; set; } // EmployeeName (length: 500)
        public string CustomerName { get; set; } // CustomerName (length: 500)
        public short? RateLevel { get; set; } // RateLevel
        public string FeedBack { get; set; } // FeedBack (length: 500)
    }

}
// </auto-generated>
